### ISSUE TITLE
Null value of datePosted field in 2010-2015 Job Posting datasets

### ISSUE THREAD

**Issue by subhashjaini** [OpenData-CS-VT/ccars-jobpostings#1]
on the tsv files, the dataPosted is null.
when I opened the json part 1, it matches the tsv
http://opendata.cs.vt.edu/dataset/2002e48d-363e-40d1-9d1b-a134301126a7/resource/d40efa75-ed86-4a01-9854-90d27539d477/download/joblistings.merged.parsed.unique.grpbyyear.2010-2015.01.json

**Comment by subhashjaini** [comment]
oh !! I think i figured it out, the links might not be updated

http://opendata.cs.vt.edu/dataset/2002e48d-363e-40d1-9d1b-a134301126a7/resource/d40efa75-ed86-4a01-9854-90d27539d477/download/joblistings.merged.parsed.unique.grpbyyear.2010-2015.01.json

works fine :)

**Comment by subhashjaini** [comment]
2016 works, the historical is givin issues

**Comment by rupenp** [comment]
Unfortunately, the raw data source for this historical dataset (2010 -- 2015 Job Postings) did not contain any field related to "date-posted" information.  Hence those values are 'null' in 2010-2015 datasets.

**Comment by subhashjaini** [comment]
No worries! :) Luckily, the 2016 set has it, which means as time goes on, everybody's apps will be better :D
