### ISSUE TITLE
Links are down

### ISSUE THREAD

**Issue by akarve** [OpenData-CS-VT/ccars-jobpostings#2]
Hi. The links to actual data here https://github.com/OpenData-CS-VT/ccars-jobpostings/wiki#data-access
plus this link are all down http://opendata.cs.vt.edu/dataset?groups=job-postings

**Comment by rupenp** [comment]
Hi Everyone,

Sorry for abrupt interruption and any inconvenience it might have caused. We're trying to scale up our backend data workflow management and REST APIs. We are looking at a mid-May time-frame for the portal and the corresponding links to be back up.

We are currently focussed on providing a full-featured Open Jobs API through opendata.cs.vt.edu, focussing on job listings tagged with JobPosting schema, available online incl. social media. Other than the primary dataset of job-listings, additional datasets that will be gradually rolled out will be related to workforce analytics and our ML-based data normalization efforts for the job postings.

**Comment by rupenp** [comment]
Datasets & API are back up online. Pls refer to wiki page for changes.
